apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "my-quarkus-app-614"
  annotations:
    argocd/app-name: my-quarkus-app-614-dev
    backstage.io/kubernetes-id: my-quarkus-app-614
    backstage.io/kubernetes-namespace: my-quarkus-app-614-dev
    janus-idp.io/tekton-enabled : 'true'
    github.com/project-slug: ultraJeffOrg/my-quarkus-app-614
    backstage.io/techdocs-ref: dir:.
  tags:
    - java
    - quarkus
  links:
    - url: https://devspaces.apps.cluster-rrhxg.rrhxg.sandbox84.opentlc.com/#https://github.com/ultraJeffOrg/my-quarkus-app-614?che-editor=che-incubator/che-code/insiders&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: https://devspaces.apps.cluster-rrhxg.rrhxg.sandbox84.opentlc.com/#https://github.com/ultraJeffOrg/my-quarkus-app-614?che-editor=che-incubator/che-idea/latest&devfilePath=.devfile-intellij.yaml
      title: OpenShift Dev Spaces (JetBrains IntelliJ)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "jeff"
  providesApis:
    - "my-quarkus-app-614"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "my-quarkus-app-614"
spec:
  type: openapi
  lifecycle: production
  owner: "jeff"
  definition:
    $text: ./openapi.yaml
